[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "web-build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "@netlify/plugin-copy"
[plugins.inputs]
source = "service-worker.js"
destination = "web-build/service-worker.js"
